# Default deployment from https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#creating-a-deployment
# Adding resource limits and requests: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/#example-1
apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthy-nginx-deployment
  labels:
    app: healthy-nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: healthy-nginx
  template:
    metadata:
      labels:
        app: healthy-nginx
    spec:
      containers:
      - name: healthy-nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "250m"
            memory: "128Mi"
          requests:
            cpu: "50m"
            memory: "64Mi"